services:
  landingpage-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: landingpage-backend
    ports:
      - "3000:5000"  # Map container port 5000 to host port 3000
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - landingpage-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  logs:

networks:
  landingpage-network:
    driver: bridge